# templates/database/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}-db-config
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
data:
  # Database connection pool configuration
  db-config.properties: |
    # Connection pool settings
    spring.datasource.hikari.maximum-pool-size={{ .Values.database.pool.maxPoolSize | default 10 }}
    spring.datasource.hikari.minimum-idle={{ .Values.database.pool.minIdle | default 5 }}
    spring.datasource.hikari.idle-timeout={{ .Values.database.pool.idleTimeout | default 300000 }}
    spring.datasource.hikari.connection-timeout={{ .Values.database.pool.connectionTimeout | default 20000 }}
    spring.datasource.hikari.max-lifetime={{ .Values.database.pool.maxLifetime | default 1200000 }}
    spring.datasource.hikari.auto-commit={{ .Values.database.pool.autoCommit | default true }}
    
    # Connection testing
    spring.datasource.hikari.connection-test-query=SELECT 1
    spring.datasource.hikari.validation-timeout=5000
    
    # Leak detection
    spring.datasource.hikari.leak-detection-threshold=30000
    
    # PostgreSQL specific settings
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
    
    # Camunda specific database settings
    camunda.bpm.database.type=postgres
    camunda.bpm.database.schema-update=true
    
    # Database performance settings
    spring.jpa.properties.hibernate.jdbc.batch_size=50
    spring.jpa.properties.hibernate.order_inserts=true
    spring.jpa.properties.hibernate.order_updates=true
    spring.jpa.properties.hibernate.batch_versioned_data=true

  # Flyway migration configuration
  flyway.properties: |
    spring.flyway.enabled=true
    spring.flyway.locations=classpath:db/migration/postgres
    spring.flyway.baseline-on-migrate=true
    spring.flyway.baseline-version=0
    spring.flyway.table=schema_version