# templates/database/secret.yaml
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}-db-credentials
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  # If using built-in PostgreSQL, use those credentials
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  {{- else }}
  # If using external database, use provided credentials
  username: {{ .Values.database.username | b64enc | quote }}
  password: {{ .Values.database.password | b64enc | quote }}
  {{- end }}
{{- end }}