# templates/istio/destinationrule.yaml
{{- if and .Values.istio.enabled .Values.istio.destinationRule.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
spec:
  host: {{ include "camunda-bpm-platform.fullname" . }}
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: {{ .Values.istio.destinationRule.connectionPool.tcp.maxConnections }}
        connectTimeout: {{ .Values.istio.destinationRule.connectionPool.tcp.connectTimeout }}
        tcpKeepalive:
          time: 7200s
          interval: 75s
      http:
        http2MaxRequests: {{ .Values.istio.destinationRule.connectionPool.http.http2MaxRequests }}
        maxRequestsPerConnection: {{ .Values.istio.destinationRule.connectionPool.http.maxRequestsPerConnection }}
        maxRetries: {{ .Values.istio.destinationRule.connectionPool.http.maxRetries }}
        idleTimeout: 15s
    outlierDetection:
      consecutive5xxErrors: {{ .Values.istio.destinationRule.outlierDetection.consecutive5xxErrors }}
      interval: {{ .Values.istio.destinationRule.outlierDetection.interval }}
      baseEjectionTime: {{ .Values.istio.destinationRule.outlierDetection.baseEjectionTime }}
      maxEjectionPercent: {{ .Values.istio.destinationRule.outlierDetection.maxEjectionPercent }}
    loadBalancer:
      simple: ROUND_ROBIN
    tls:
      mode: ISTIO_MUTUAL
  subsets:
    - name: v1
      labels:
        version: v1
{{- end }}