# templates/istio/peerauthentication.yaml
{{- if and .Values.istio.enabled .Values.istio.peerAuthentication.enabled }}
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: {{ include "camunda-bpm-platform.fullname" . }}
  labels:
    {{- include "camunda-bpm-platform.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "camunda-bpm-platform.selectorLabels" . | nindent 6 }}
  mtls:
    mode: {{ .Values.istio.peerAuthentication.mtls.mode }}
  
  # Port-specific mTLS settings if configured
  {{- with .Values.istio.peerAuthentication.portLevelMtls }}
  portLevelMtls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}